### ISSUE TITLE
In order to use ec2-automate-backup.sh, the executable "ec2-create-snapshot" must be installed

### ISSUE THREAD

**Issue by hydn79** [colinbjohnson/aws-missing-tools#36]
I installed and tried running it. I get:
In order to use ec2-automate-backup.sh, the executable "ec2-create-snapshot" must be installed

Where do I download and put that? Its not on my EC2 server.

**Comment by abrookewood** [comment]
Assuming that you have the prerequisites installed and that running the command manually works, but not in Cron, it may be that the correct path is not exposed to the cron command. You can fix this by running crontab -e and then entering the path directly into the cron tab:

# Export the path so that the scripts run correctly
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin
